y <- theme(legend.key = element_rect(fill = "white"),
           legend.background = element_blank(),
           legend.text=element_text(size=12),
           legend.title=element_text(size=12, face="bold"),
           panel.background = element_rect(fill = "white", colour="black"),
           panel.grid.major = element_blank(),
           panel.grid.minor = element_blank(),
           legend.position = "right",
           strip.background = element_rect(fill = "lightblue", color = "black", size = .5),
           strip.text.x = element_text(size=12),
           axis.text.y=element_text(size=11),
           axis.title.y=element_text(size=12, face="bold"),
           axis.text.x=element_text(size=11),
           axis.title.x=element_text(size=12, face="bold"),
           plot.title=element_text(size=12))